# Generated by Django 5.1.1 on 2024-10-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_payment',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='user',
            new_name='user_payment',
        ),
    ]
