# Generated by Django 5.1.1 on 2024-10-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_user_payment_user_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_payment',
            new_name='account_user',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='user_payment',
            new_name='account_user',
        ),
    ]
