name: Deploy to App Engine

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'setup'
      name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - id: 'dependencies'
      name: Install dependencies
      run: |
        pip install -r requirements.txt
        python manage.py collectstatic

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/207118337963/locations/global/workloadIdentityPools/github-pool/providers/github-actions'
        service_account: 'github-actions@fairpay-438003.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        working_directory: ./app
        version: 'dev'
        promote: false